### ISSUE TITLE
Logo and color scheme

### ISSUE THREAD

**Issue by antisunshine** [antisunshine/aimo#6]

**Comment by SumiyaC** [comment]
![Image](https://user-images.githubusercontent.com/102297880/197289990-8b48d5f6-a120-4719-a2b8-1cb708c27298.png)
![Image](https://user-images.githubusercontent.com/102297880/197289991-1e32d981-8c15-429d-b1a9-2ac8fd75594d.png)
![Image](https://user-images.githubusercontent.com/102297880/197289989-3d499d8a-c4f5-464e-bc22-54575741a9ff.png)

**Comment by SumiyaC** [comment]
I used this to make the logo..from what i understood, it is okay to use this for this project purpose right??

![Image](https://user-images.githubusercontent.com/102297880/197290314-b97e8484-434a-4ae2-a5b7-4c171ff3f9f7.png)

**Comment by antisunshine** [comment]
I like it! I think it's ok to use. We just can't sell the graphics itself, but we're not in the business of selling graphics.

**Comment by SumiyaC** [comment]
I think the colour is good and I like 2nd row 1st and last one more with white background

**Comment by AnnaElo** [comment]
I also like the 2nd row's first logo. It's simple and I like the green color.

**Comment by sadikshya2001** [comment]
I like the second row 1st and 2nd logo.

**Comment by antisunshine** [comment]
I'll leave in a couple variants we can use depending on what background colors we want to use for any situation. I'll convert to different filetypes and sizes when needed.

![Image](https://user-images.githubusercontent.com/68944550/198555776-2c0358f7-1a9e-4e78-9012-6cc13d1e575f.png)

**Comment by SumiyaC** [comment]
![Image](https://user-images.githubusercontent.com/102297880/199002713-9e14ecbe-ed56-4d6c-85e7-2d84dd40955e.png)



![Image](https://user-images.githubusercontent.com/102297880/199002739-a9945b1c-fcd6-453e-ae74-e781f0ec95d9.png)
