### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by antisunshine** [antisunshine/aimo#7]
https://www.canva.com/design/DAFQnFIGEx0/rbEc1ZsYqetI9UZ-Wzyabg/view?utm_content=DAFQnFIGEx0&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

View only link for presentation. Confirm that it works.

**Comment by SumiyaC** [comment]
I prefer ppt..we can use canva to make slides
