### ISSUE TITLE
Persona

### ISSUE THREAD

**Issue by sadikshya2001** [antisunshine/aimo#8]

**Comment by sadikshya2001** [comment]
![1](https://user-images.githubusercontent.com/71209563/197342678-9d0b3e3c-6cdf-4395-a3a1-bdda1930c31e.jpg)
![2](https://user-images.githubusercontent.com/71209563/197342679-23d5b175-52eb-4cd6-bbfa-650f955b0251.jpg)

**Comment by sadikshya2001** [comment]
@everyone, What do you think of this??

**Comment by antisunshine** [comment]
Theese look great!

**Comment by SumiyaC** [comment]
looks good.
